### ISSUE TITLE
after 45 eth address Checked crash

### ISSUE THREAD

**Issue by sec13b** [niyankhadka/crypto-wallet-bruteforce#2]
Total Checked: 45 || Execution Per Time: 0:00:31.233903 || Elapsed Time: 0:04:10.316960
Transaction Found: 0 || Balance Found: 0
Checking Mnemonic: ............hide....................
Wallet Address: 
---->>> Checking Transaction(s) on bsc
Traceback (most recent call last):
  File "/home/kali/Desktop/CWB/run.py", line 207, in <module>
    main()
  File "/home/kali/Desktop/CWB/run.py", line 163, in main
    if wallet_trnx_status["status"] == "1":
       ~~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by niyankhadka** [comment]
Hi, 
Just to confirm, have you created api of bsc, eth and polygon from your personal account?
There is no need of contract address. Just need api keys and you need to copy paste api keys. 
For guidance,  there is link to documentation of How to create api and use it. 
Check below screenshot for reference 👇👇
![Screenshot_20231226-151709_Chrome](https://github.com/niyankhadka/crypto-wallet-bruteforce/assets/24240246/b521e9ac-97a2-4585-9e4e-865c550c0222)

**Comment by niyankhadka** [comment]
Also, sometimes the issue might arise due to the API connection lost due to internet connections or response from the API might be rejected/limited. 

As further response is not from your side, so closing this issue for now.
