### ISSUE TITLE
Any chance to increase speed

### ISSUE THREAD

**Issue by alt33d** [niyankhadka/crypto-wallet-bruteforce#4]
How could you increase speed on such a program? I think it would have to change from python to maybe java or somehow multithread the application. doing the probability math shows that theres a super slim chance that we ever find anything at this speed :)

**Comment by alt33d** [comment]
Sounds great

**Comment by niyankhadka** [comment]
Since there is no response at all, i will be closing this issue for now. Feel happy to raise the issue if you face any kind of problems. Also, new version is on the way. :)
