### ISSUE TITLE
It needs to be revised.

### ISSUE THREAD

**Issue by KYC27** [niyankhadka/crypto-wallet-bruteforce#6]
Hello my friend. I run it from cmd. I haven't achieved anything for 3 months. The program is not working. If you have the latest version, can you update it? Sometimes the program itself suddenly stops working.

**Comment by niyankhadka** [comment]
Hi, 
Thank you for using my script. I am aware of the issue you are facing. Program is generating random menmonic phrase from billions of combination,  so it can be years of years to find. So, if we get enough luck, then it will find it. 

Though it is taking 4 to 5 seconds to check one address for multiple network checking, it is slower. So, i am making v2 of it and is under testing purpose to support btc, bsc, eth, polygon, tron and sol networks. Also, the time is reduced in range of 0.5 to 1 sec for 1 address supporting 6 networks.

So, next v2 is on the way which is faster and more compatible with long term run. Please do wait for next version. I will release it soon asap when testing period is successful. 

Regards

**Comment by KYC27** [comment]
I'm waiting for v2 with curiosity.  If there is something I need to help with, I can help.  I support you, my friend.

**Comment by niyankhadka** [comment]
FYI, v2 is almost ready to be available soon, and the testing phase is showing good results. 
As there are no further comments, I am closing this thread.
